[workspace]
resolver = "2"
members = [
    "ruby-marshal",
    "ruby-marshal-cli", "ruby-marshal-derive",
]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = "symbols"
panic = "abort"
